version: "3.6"

services:
  db:
    image: mysql:5.6
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
    network_mode: service:web
    volumes:
      - mysql_data:/var/lib/mysql
      - mysql_socket:/var/run/mysqld/

  phpmyadmin:
    build: 
      context: .
      dockerfile: phpmyadmin.dockerfile
    environment:
      PMA_HOST: web
    ports:
      - 8081:80

  web:
    build:
      context: .
      dockerfile: php.dockerfile
    ports:
      - 8080:80
    volumes:
      - ${PWD}:/var/www/html
      - mysql_socket:/var/run/mysqld/

volumes:
  mysql_data:
  mysql_socket: