DISTRO=$(cat /etc/issue | awk '{ print $1 }')

DOTFILES=$HOME/.dotfiles
ZSH=$DOTFILES/zsh

TERM="xterm-256color"


# source all .zsh files inside of the zsh/ subdirectory
for config ($ZSH/**/*.zsh) source $config


# ZPlug
#-------------
ZPLUG_HOME=$HOME/.zplug
ZPLUG_LOADFILE="$ZSH/zplug.packages.list"

# Install zplug if not installed

[[ -d $ZPLUG_HOME ]] || {
	git clone --depth 1 https://github.com/zplug/zplug $ZPLUG_HOME
}

source $ZPLUG_HOME/init.zsh

# Install plugins that have not been installed yet
zplug check || zplug install

zplug load

if zplug check bhilburn/powerlevel9k; then
  DEFAULT_USER=${USER}
  POWERLEVEL9K_PROMPT_ON_NEWLINE=true
  POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(custom_ccontext dir vcs)
  POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status custom_nodenv time)
  POWERLEVEL9K_SHORTEN_DIR_LENGTH=3
  POWERLEVEL9K_CUSTOM_CCONTEXT="hostname"
  POWERLEVEL9K_CUSTOM_CCONTEXT_BACKGROUND="238"
  POWERLEVEL9K_CUSTOM_CCONTEXT_FOREGROUND="252"
  POWERLEVEL9K_DIR_BACKGROUND='238'
  POWERLEVEL9K_DIR_FOREGROUND='252'
  POWERLEVEL9K_STATUS_BACKGROUND='238'
  POWERLEVEL9K_STATUS_FOREGROUND='252'
  POWERLEVEL9K_CONTEXT_BACKGROUND='240'
  POWERLEVEL9K_CONTEXT_FOREGROUND='252'
  POWERLEVEL9K_TIME_BACKGROUND='238'
  POWERLEVEL9K_TIME_FOREGROUND='252'
  POWERLEVEL9K_CUSTOM_NODENV="nodenv version | awk '{print \$1}'"
  POWERLEVEL9K_CUSTOM_NODENV_BACKGROUND='240'
  POWERLEVEL9K_CUSTOM_NODENV_FOREGROUND='252'
  POWERLEVEL9K_HISTORY_BACKGROUND='240'
  POWERLEVEL9K_HISTORY_FOREGROUND='252'
fi

if zplug check "zsh-users/zsh-history-substring-search"; then
  # Add history-substring-search-* widgets to list of widgets that clear the autosuggestion
  ZSH_AUTOSUGGEST_CLEAR_WIDGETS+=(history-substring-search-up history-substring-search-down)
fi

if zplug check "zsh-users/zsh-autosuggestions"; then
  bindkey '^ ' autosuggest-accept
fi

if zplug check "Tarrasch/zsh-autoenv"; then
  AUTOENV_FILE_ENTER=.env
  AUTOENV_FILE_LEAVE=.envl
fi

export PATH="$ZPLUG_BIN:$PATH"
